services:
  wp:
    image: wordpress:latest
    ports:
      - "8888:80"
    volumes:
      - ./:/var/www/html/wp-content/plugins/wp-avorg-multisite-catalog
    environment:
      - WORDPRESS_DB_HOST=db
      - WORDPRESS_DB_USER=dbuser
      - WORDPRESS_DB_PASSWORD=dbpass
      - WORDPRESS_DB_NAME=wordpress
      - WORDPRESS_DEBUG=1
  db:
    image: mysql:5.7
    restart: always
    volumes:
      - ./db:/var/lib/mysql
    environment:
      MYSQL_DATABASE: wordpress
      MYSQL_USER: dbuser
      MYSQL_PASSWORD: dbpass
      MYSQL_RANDOM_ROOT_PASSWORD: "1"

